version: "3.9"

services:
  backend:
    build: ./backend
    expose:
      - "8080"
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge
