services:
  backend:
    build: ./backend
    expose:
      - "8080"
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge
